.TH CINNAMON-SETTINGS 1 2012-07-23  Cinnamon "cinnamon manual"
.SH NAME
cinnamon-settings \- Configuration panel for cinnamon
.SH SYNOPSIS
.SY cinnamon-settings
.SH DESCRIPTION
.LP
\fBcinnamon-settings\fP runs the graphical user interface allowing to
configure cinnamon
.SH "SEE ALSO"
.BR cinnamon-menu-editor (1)

