.TH CINNAMON-SETTINGS 1 2019-02-10  Cinnamon "cinnamon manual"
.SH NAME
cinnamon-settings \- Configuration panel for cinnamon
.SH SYNOPSIS
.B cinnamon-settings [-h]
.br
\fBcinnamon-settings\fP MODULE [\fB-t\fP TAB]
.br
\fBcinnamon-settings\fP \fBapplets\fP|\fBpanel\fP [\fB-p\fP PANEL]
.br
\fBcinnamon-settings\fP \fBapplets\fP|\fBdesklets\fP|\fBextensions\fP|\fBthemes\fP|\fBactions\fP [\fB-t\fP TAB]
.br
\fBcinnamon-settings\fP \fBapplets\fP|\fBdesklets\fP|\fBextensions\fP|\fBthemes\fP|\fBactions\fP -t download\fP [\fB-s\fP SORT]
.SH DESCRIPTION
.LP
\fBcinnamon-settings\fP runs the graphical user interface allowing to configure Cinnamon. Command line arguments can be used to open a specific module and even a tab within that module.
.br

Run \fBcinnamon-settings --help\fP to see a list of modules.
.br
Run \fBcinnamon-settings MODULE --tab help\fP to see the available tabs for a particular module.

.SH PANEL
When the \fBapplets\fP or \fBpanel\fP module are specified, PANEL can specify the id of a specific panel operate on.

.SH SORT
.TP
Possible choices are:
.br
 - \fBname\fP or \fB0\fP
.br
 - \fBscore\fP or \fB1\fP (default value)
.br
 - \fBdate\fP or \fB2\fP
.br
 - \fBinstalled\fP or \fB3\fP
.br
 - \fBupdate\fP or \fB4\fP (upgradable Spices first, then acts as \fBdate\fP)

.SH OPTIONS
The following options are supported:
.TP
\fB-h\fP, \fB--help\fP
Print a help text describing the supported command-line options, and then exit.
.TP
\fB-s\fP SORT, \fB--sort=\fPSORT
Specific to the 'download' tab (see below) for \fBapplets\fP, \fBdesklets\fP, \fBextensions\fP, \fBthemes\fP and \fBactions\fP modules.
.TP
\fB-t\fP TAB, \fB--tab=\fPTAB
Select the tab to switch to in the module. Specifying \fB--tab=help\fP will print a module's available tab names then exit. Not all modules have multiple tabs.
.TP
\fB-p\fP PANEL, \fB--panel=\fPPANEL
Select the panel ID to operate on. Only valid with the applets and panel modules.


.SH EXAMPLES
.TP
To open System Settings:
$ \fBcinnamon-settings\fP

.TP
To add some applets on the second panel (if it exists):
$ \fBcinnamon-settings applets --panel 2\fP
.TP
To open the download tab of the applets module:
$ \fBcinnamon-settings applets --tab=download\fP
.br
or
.br
$ \fBcinnamon-settings applets -t 1\fP

.TP
To open the applets download tab and sort by 'name':
.br
$ \fBcinnamon-settings applets --tab=download --sort=name\fP
.br
or
.br
$ \fBcinnamon-settings applets -t 1 -s 0\fP
.br

.SH "SEE ALSO"
.BR cinnamon-menu-editor (1)

.SH "CONTRIBUTORS"
Claude Clerc (claudiux) and Nicolas Bourdaud (nbourdau).
