.TH CINNAMON-EXTENSION-TOOL 1 2012-07-23  Cinnamon "cinnamon manual"
.SH NAME
cinnamon-extension-tool \- extension management program
.SH SYNOPSIS
.SY cinnamon-extension-tool
.OP \-\-create-extension
.br
.SH DESCRIPTION
.LP
\fBcinnamon-extension-tool\fP runs the graphical user interface allowing to
manage the extensions to be used in cinnamon.
.SH "SEE ALSO"
.BR cinnamon-settings (1)

