.TH CINNAMON-LAUNCHER 1 2012-07-29  Cinnamon "cinnamon manual"
.SH NAME
cinnamon-launcher \- Start or restart a cinnamon session
.SH SYNOPSIS
.SY cinnamon-launcher
.SH DESCRIPTION
.LP
\fBcinnamon-launcher\fP runs the graphical user interface allowing to
start or restart a session of cinnamon desktop.
.SH "SEE ALSO"
.BR cinnamon (1)

