.TH CINNAMON-LOOKING-GLASS 1 2013-03-08  Cinnamon "cinnamon manual"
.SH NAME
cinnamon-looking-glass \- Debugging interface for Cinnamon
.SH SYNOPSIS
.SY cinnamon-looking-glass
.SH DESCRIPTION
.LP
.B cinnamon-looking-glass
runs the graphical debugger interface for cinnamon.
.SH AUTHOR
.B cinnamon-looking-glass
is written by the Mint project <root@linuxmint.com>.
.P
This manual page was written by Nicolas Bourdaud
<nicolas.bourdaud@gmail.com> for the Debian project.
.SH "SEE ALSO"
.BR cinnamon (1)
