.TH CINNAMON-MENU-EDITOR 1 2012-07-23  Cinnamon "cinnamon manual"
.SH NAME
cinnamon-menu-editor \- Editor for the panel menu
.SH SYNOPSIS
.SY cinnamon-menu-editor
.SH DESCRIPTION
.LP
\fBcinnamon-menu-editor\fP runs the graphical user interface allowing to
edit the menu displayed in cinnamon.
.SH "SEE ALSO"
.BR cinnamon-settings (1)

