.TH CINNAMON-SCREENSAVER-LOCK-DIALOG 1 2013-03-08  Cinnamon "cinnamon manual"
.SH NAME
cinnamon-screensaver-lock-dialog \- message setting for cinnamon screensaver
.SH SYNOPSIS
.SY cinnamon-screensaver-lock-dialog
.SH DESCRIPTION
.LP
.B cinnamon-screensaver-lock-dialog
runs the graphical interface to set an away message when executing
cinnamon-screensaver.
.SH NOTE
This dialog applet will work only if
.B cinnamon-screensaver
is installed. Therefore, cinnamon desktop will call the dialog only if the
latter is effectively installed.
.SH AUTHOR
.B cinnamon-screensaver-lock-dialog
is written by the Mint project <root@linuxmint.com>.
.P
This manual page was written by Nicolas Bourdaud
<nicolas.bourdaud@gmail.com> for the Debian project.
.SH "SEE ALSO"
.BR gnome-screensaver-command (1)
