.\" Copyright (c) 2009, Marcelo Jorge Vieira (metal) <metal@alucinados.com>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
.\" Boston, MA  02111-1301  USA.
.TH GNOME-SHELL 1
.SH NAME
gnome-shell \- Graphical shell for the GNOME desktop

.SH SYNOPSIS
.B gnome-shell [options]

.SH DESCRIPTION
GNOME Shell provides core user interface functions for the GNOME 3
desktop, like switching to windows and launching applications. GNOME
Shell takes advantage of the capabilities of modern graphics hardware
and introduces innovative user interface concepts to provide a
visually attractive and easy to use experience.

.SH OPTIONS

.TP
.B \-\-replace
Replace the running window manager
.br

.TP
.B \-\-sm-disable
Disable connection to the session manager
.br

.TP
.B \-\-sm-client-id=ID
Specify session management ID
.br

.TP
.B \-\-sm-save-file=FILE
Initialize session from savefile
.br

.TP
.B \-\-screen=SCREEN
X screen to use
.br

.TP
.B \-d, \-\-display=DISPLAY
X display to use
.br

.TP
.B \-\-sync
Make X calls synchronous
.br

.TP
.B \-\-version
Print version and exit
.br

.TP
.B \-\-help
Display help and exit
.br

.SH BUGS
The bug tracker can be reached by visiting the website
\fIhttps://bugzilla.gnome.org/buglist.cgi?product=gnome-shell\fR

Before sending a bug report, please verify that you have the latest
version of gnome-shell. Many bugs (major and minor) are fixed at each
release, and if yours is out of date, the problem may already have
been solved.

.SH ADDITIONAL INFORMATION

For further information, visit the website \fIhttp://live.gnome.org/GnomeShell\fR
