# Specify that we're C++
language: cpp

# Compiler selection
compiler:
#  - clang
  - gcc

# Configure step
before_script:
  - ./autogen.sh

# Build step
script:
  - make

#addons:
#  coverity_scan:

#build_command_prepend: ./autogen.sh

#build_command: make

