# Specify that we're C++
language: cpp
sudo: required

# Compiler selection
compiler:
#  - clang
  - gcc

# Add dependencies
#addons:
#  apt:
#    packages:
#      - intltool

# Add build-deps for cinnamon and friends
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 451BBBF2
  #- curl http://packages.linuxmint.com/dists/debian/Release.gpg | sudo apt-key add -
  - echo "deb http://packages.linuxmint.com sarah main upstream import backport" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get build-dep cinnamon

# Configure step
before_script:
  - ./autogen.sh

# Build step
script:
  - make

#addons:
#  coverity_scan:

#build_command_prepend: ./autogen.sh

#build_command: make

