#!/bin/bash

xgettext -cTranslators -cTRANSLATORS --keyword=_ --keyword=N_ --from-code=UTF-8 \
	--files-from=po/POTFILES.in --output=cinnamon.pot
xgettext -c --language=Python --keyword=_ --output=cinnamon.pot --join-existing files/usr/bin/*

files/usr/bin/cinnamon-xlet-makepot -j -p -m -o cinnamon.pot files/usr/share/cinnamon/applets/
files/usr/bin/cinnamon-xlet-makepot -j -p -m -o cinnamon.pot files/usr/share/cinnamon/desklets/
