#!/bin/bash
xgettext --language=C --keyword=_ --output=cinnamon.pot src/*.c src/*/*.c js/*/*.js files/usr/share/cinnamon/applets/*/applet.js files/usr/share/cinnamon/desklets/*/desklet.js files/usr/lib/cinnamon-settings/*.py files/usr/share/cinnamon/applets/*/*.py files/usr/share/cinnamon/desklets/*/*.py files/usr/lib/cinnamon-screensaver-lock-dialog/*.py

