#!/bin/bash
xgettext --language=C --keyword=_ --output=cinnamon.pot generate_additional_files.py src/*.c src/*/*.c js/*/*.js files/usr/share/cinnamon/applets/*/applet.js files/usr/share/cinnamon/desklets/*/desklet.js files/usr/lib/cinnamon-settings/*.py files/usr/lib/cinnamon-settings-users/*.py files/usr/lib/cinnamon-settings/modules/*.py files/usr/lib/cinnamon-settings/bin/ExtensionCore.py files/usr/lib/cinnamon-settings/bin/eyedropper.py files/usr/lib/cinnamon-settings/bin/Spices.py files/usr/lib/cinnamon-settings/bin/XletSettings.py files/usr/lib/cinnamon-settings/bin/XletSettingsWidgets.py files/usr/share/cinnamon/desklets/*/*.py files/usr/lib/cinnamon-screensaver-lock-dialog/*.py files/usr/bin/cinnamon-launcher
cd files
usr/lib/cinnamon-json-makepot/cinnamon-json-makepot.py ../cinnamon
cd ..
