#!/bin/bash

sudo rm -rf /usr/share/cinnamon/js-backup
sudo mv /usr/share/cinnamon/js /usr/share/cinnamon/js-backup
sudo cp -R debian/tmp/usr/share/cinnamon/js /usr/share/cinnamon/
sudo cp -R js /usr/share/cinnamon/

sudo rm -rf /usr/lib/cinnamon-settings
sudo rm -rf /usr/lib/cinnamon-menu-editor
sudo cp -R files/usr /
sudo cp -R files/etc /

sudo cp data/org.cinnamon.gschema.xml /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/

mkdir -p tmp
meson setup tmp
meson compile -C tmp cinnamon_css
sudo cp tmp/data/theme/cinnamon-sass/cinnamon.css /usr/share/cinnamon/theme/

sudo rm -f /usr/bin/cinnamon-settings-users
sudo rm -f /usr/share/applications/cinnamon-settings-info.desktop
sudo rm -f /usr/share/applications/cinnamon-settings-user.desktop
sudo rm -f /usr/share/applications/cinnamon-settings-users.desktop
sudo rm -f /usr/share/cinnamon/cinnamon-settings/modules/cs_info.py
sudo rm -f /usr/share/cinnamon/cinnamon-settings/modules/cs_user.py
sudo rm -rf /usr/share/cinnamon/cinnamon-settings-users
