#!/bin/bash

rm -rf /usr/share/cinnamon/js-backup
mv /usr/share/cinnamon/js /usr/share/cinnamon/js-backup
cp -R js /usr/share/cinnamon/

rm -rf /usr/share/cinnamon/theme-backup
mv /usr/share/cinnamon/theme /usr/share/cinnamon/theme-backup
cp -R data/theme /usr/share/cinnamon/
