#! /bin/sh
### BEGIN INIT INFO
# Provides:          cinnamon
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Cinnamon cache preloader
### END INIT INFO

set -e

case "$1" in
  start|restart)
        su -c cinnamon-preload-wrapper
  ;;
  stop)
        exit 0
  ;;
  *)
        echo "Usage: /etc/init.d/cinnamon {start}"
        exit 1
  ;;
esac

exit 0
