#!/bin/sh
# Internal screensaver cleanup
killall cinnamon-backup-locker 2>/dev/null
gsettings set org.cinnamon session-locked-state false
# Legacy cinnamon-screensaver cleanup
killall cs-backup-locker 2>/dev/null
killall cinnamon-screensaver 2>/dev/null
