name: Pattern Check

on:
    pull_request:
        branches: [ master ]

permissions:
    pull-requests: write

jobs:
    pattern-check:
        name: Pattern Check
        runs-on: ubuntu-latest

        steps:
            - name: Checkout github-actions
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  repository: linuxmint/github-actions
                  path: _github-actions

            - name: Pattern Check
              uses: ./_github-actions/pattern-checker
              with:
                  github_token: ${{ github.token }}
